version: '3'

services:
  dash_app:
    container_name: dash_app
    restart: always
    build: ./dash_app
    volumes:
      - ./dash_app:/repos/dashconda/dash_app
    ports:
      - "8050:8050"
    stdin_open: true
    tty: true
    #command: conda run -n myenv bash -c 'python /repos/dashconda/dash_app/app.py'
    command: gunicorn -w 1 -b 0.0.0.0:8050 repos.dashconda.dash_app.app:server
  
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - dash_app
